apiVersion: apps/v1
kind: Deployment
metadata:
  name: japo-ambulance-webapi
spec:
  replicas: 1
  selector:
      matchLabels:
        pod: japo-ambulance-webapi-label
  template:
      metadata:
        labels:
          pod: japo-ambulance-webapi-label
      spec:
        containers:
        - name: japo-ambulance-wl-webapi-container
          image: <docker-id>/ambulance-wl-webapi:latest
          imagePullPolicy: Always
          ports:
          - name: webapi-port
            containerPort: 8080
          env:
            - name: AMBULANCE_API_ENVIRONMENT
              value: production
            - name: AMBULANCE_API_PORT
              value: "8080"
            - name: AMBULANCE_API_MONGODB_HOST
              value: mongodb
            - name: AMBULANCE_API_MONGODB_PORT
              value: "27017"
              # change to actual value
            - name: AMBULANCE_API_MONGODB_USERNAME
              value: ""
              #change to actual value
            - name: AMBULANCE_API_MONGODB_PASSWORD
              value: ""
            - name: AMBULANCE_API_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: japo-ambulance-webapi-config
                  key: database
            - name: AMBULANCE_API_MONGODB_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: japo-ambulance-webapi-config
                  key: collection
            - name: AMBULANCE_API_MONGODB_TIMEOUT_SECONDS
              value: "5"
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.01"
            limits:
              memory: "512Mi"
              cpu: "0.3"
